spring:
  datasource:
    # 配置数据源类型

    driverclassname: com.mysql.cj.jdbc.Driver
    password: 123
    url: jdbc:mysql://192.168.133.7:13306/how2java?characterEncoding=UTF-8
    username: root
server:
  port: 8001